INSERT INTO categories VALUES (1,'Accesorios para Vehículos',NULL,'accesorios-para-vehiculos');
INSERT INTO categories VALUES (50,'Accesorios y Repuestos Náuticos',1,'accesorios-y-repuestos-nauticos');
INSERT INTO categories VALUES (51,'Accesorios y Repuestos para Carros',1,'accesorios-y-repuestos-para-carros');
INSERT INTO categories VALUES (52,'Accesorios y Repuestos para Motos',1,'accesorios-y-repuestos-para-motos');
INSERT INTO categories VALUES (53,'Accesorios y Repuestos para Rústicos',1,'accesorios-y-repuestos-para-rusticos');
INSERT INTO categories VALUES (2,'Animales y Mascotas',NULL,'animales-y-mascotas');
INSERT INTO categories VALUES (54,'Alimentación para Animales',2,'alimentacion-para-animales');
INSERT INTO categories VALUES (55,'Accesorios Aves',2,'accesorios-aves');
INSERT INTO categories VALUES (56,'Accesorios Caballos',2,'accesorios-caballos');
INSERT INTO categories VALUES (57,'Accesorios Ganado',2,'accesorios-ganado');
INSERT INTO categories VALUES (58,'Accesorios para Peceras',2,'accesorios-para-peceras');
INSERT INTO categories VALUES (3,'Bebés',NULL,'bebes');
INSERT INTO categories VALUES (59,'Alimentación para Bebés',3,'alimentacion-para-bebes');
INSERT INTO categories VALUES (60,'Artículos de Bebés para Baño',3,'articulos-de-bebes-para-baño');
INSERT INTO categories VALUES (61,'Accesorios para Bebés',3,'accesorios-para-bebes');
INSERT INTO categories VALUES (4,'Cámaras y Accesorios',NULL,'camaras-y-accesorios');
INSERT INTO categories VALUES (62,'Accesorios para Cámaras',4,'accesorios-para-camaras');
INSERT INTO categories VALUES (63,'Cámaras Convencionales',4,'camaras-convencionales');
INSERT INTO categories VALUES (64,'Cámaras Digitales',4,'camaras-digitales');
INSERT INTO categories VALUES (65,'Memorias Digitales',4,'memorias-digitales');
INSERT INTO categories VALUES (66,'Video Cámaras',4,'video-camaras2');
INSERT INTO categories VALUES (5,'Celulares y Teléfonos',NULL,'celulares-y-telefonos');
INSERT INTO categories VALUES (67,'Accesorios para Celulares',5,'accesorios-para-celulares');
INSERT INTO categories VALUES (68,'Celulares',5,'celulares');
INSERT INTO categories VALUES (69,'Radios - WalkieTalkies',5,'radios--walkietalkies');
INSERT INTO categories VALUES (70,'Telefonía',5,'telefonia2');
INSERT INTO categories VALUES (6,'Computación',NULL,'computacion');
INSERT INTO categories VALUES (71,'Accesorios para Laptops',6,'accesorios-para-laptops');
INSERT INTO categories VALUES (72,'Apple',6,'apple');
INSERT INTO categories VALUES (73,'Cartuchos, Tintas y Toner',6,'cartuchos-tintas-y-toner');
INSERT INTO categories VALUES (74,'Computadoras',6,'computadoras');
INSERT INTO categories VALUES (75,'Discos Duros y Removibles',6,'discos-duros-y-removibles');
INSERT INTO categories VALUES (76,'Impresoras y Plotters',6,'impresoras-y-plotters');
INSERT INTO categories VALUES (77,'Laptops',6,'laptops');
INSERT INTO categories VALUES (78,'Memorias Portátiles USB',6,'memorias-portatiles-usb');
INSERT INTO categories VALUES (79,'Memorias RAM',6,'memorias-ram');
INSERT INTO categories VALUES (80,'Monitores',6,'monitores');
INSERT INTO categories VALUES (81,'Periféricos y Accesorios de PC',6,'perifericos-y-accesorios-de-pc');
INSERT INTO categories VALUES (82,'Procesadores',6,'procesadores');
INSERT INTO categories VALUES (83,'Proyectores y Pantallas',6,'proyectores-y-pantallas');
INSERT INTO categories VALUES (84,'Redes Inalámbricas y No Inalámbricas',6,'redes-inalambricas-y-no-inalambricas');
INSERT INTO categories VALUES (85,'Registradoras y Punto de Venta',6,'registradoras-y-punto-de-venta');
INSERT INTO categories VALUES (86,'Software',6,'software');
INSERT INTO categories VALUES (87,'Tarjetas Madre',6,'tarjetas-madre');
INSERT INTO categories VALUES (88,'Tarjetas de Video y Captura',6,'tarjetas-de-video-y-captura');
INSERT INTO categories VALUES (89,'iPad y Tablets',6,'ipad-y-tablets');
INSERT INTO categories VALUES (7,'Deportes y Fitness',NULL,'deportes-y-fitness');
INSERT INTO categories VALUES (90,'Aerobics y Fitness',7,'aerobics-y-fitness');
INSERT INTO categories VALUES (91,'Artes Marciales y Boxeo',7,'artes-marciales-y-boxeo');
INSERT INTO categories VALUES (92,'Beisbol, Futból, Basquet, Tenis, Golf',7,'beisbol-futbol-basquet-tenis-golf');
INSERT INTO categories VALUES (93,'Bicicletas y Ciclismo',7,'bicicletas-y-ciclismo');
INSERT INTO categories VALUES (94,'Camping',7,'camping');
INSERT INTO categories VALUES (95,'Deportes Acuáticos',7,'deportes-acuaticos');
INSERT INTO categories VALUES (96,'Deportes Extremos',7,'deportes-extremos');
INSERT INTO categories VALUES (97,'Equipos para Pesca',7,'equipos-para-pesca');
INSERT INTO categories VALUES (98,'Lentes Deportivos y de Sol',7,'lentes-deportivos-y-de-sol');
INSERT INTO categories VALUES (99,'Máquinas de Gimnasio',7,'maquinas-de-gimnasio');
INSERT INTO categories VALUES (100,'Morrales, Koalas y Maletines',7,'morrales-koalas-y-maletines');
INSERT INTO categories VALUES (8,'Electrodomésticos',NULL,'electrodomesticos');
INSERT INTO categories VALUES (101,'Aires Acondicionados',8,'aires-acondicionados');
INSERT INTO categories VALUES (102,'Artefactos para el Hogar',8,'artefactos-para-el-hogar');
INSERT INTO categories VALUES (103,'DVDs y Home Theaters',8,'dvds-y-home-theaters');
INSERT INTO categories VALUES (104,'Electrodomésticos de Cocina',8,'electrodomesticos-de-cocina');
INSERT INTO categories VALUES (105,'Lavadoras y Secadoras',8,'lavadoras-y-secadoras');
INSERT INTO categories VALUES (106,'Neveras y Congeladores',8,'neveras-y-congeladores');
INSERT INTO categories VALUES (107,'Televisores',8,'televisores');
INSERT INTO categories VALUES (108,'Ventiladores',8,'ventiladores');
INSERT INTO categories VALUES (9,'Electrónica, Audio y Video',NULL,'electronica-audio-y-video');
INSERT INTO categories VALUES (109,'Accesorios para Audio y Video',9,'accesorios-para-audio-y-video');
INSERT INTO categories VALUES (110,'Audio Portátil y Radios',9,'audio-portatil-y-radios');
INSERT INTO categories VALUES (111,'Audio Profesional y DJs',9,'audio-profesional-y-djs');
INSERT INTO categories VALUES (112,'Audio para Carros',9,'audio-para-carros');
INSERT INTO categories VALUES (113,'Audio para el Hogar',9,'audio-para-el-hogar');
INSERT INTO categories VALUES (114,'Calculadoras',9,'calculadoras');
INSERT INTO categories VALUES (115,'DVDs y Home Theaters',9,'dvds-y-home-theaters2');
INSERT INTO categories VALUES (116,'Fotocopiadoras y Accesorios',9,'fotocopiadoras-y-accesorios');
INSERT INTO categories VALUES (117,'GPS y Accesorios',9,'gps-y-accesorios');
INSERT INTO categories VALUES (118,'Reproductores MP3, MP4 y MP5',9,'reproductores-mp3-mp4-y-mp5');
INSERT INTO categories VALUES (119,'Seguridad para el Hogar',9,'seguridad-para-el-hogar');
INSERT INTO categories VALUES (120,'Televisores',9,'televisores2');
INSERT INTO categories VALUES (121,'Video Cámaras',9,'video-camaras');
INSERT INTO categories VALUES (10,'Hogar y Muebles',NULL,'hogar-y-muebles');
INSERT INTO categories VALUES (122,'Baño',10,'baño');
INSERT INTO categories VALUES (123,'Cocina',10,'cocina');
INSERT INTO categories VALUES (124,'Decoración',10,'decoracion');
INSERT INTO categories VALUES (125,'Dormitorio',10,'dormitorio');
INSERT INTO categories VALUES (126,'Herramientas para el Hogar',10,'herramientas-para-el-hogar');
INSERT INTO categories VALUES (127,'Iluminación para el Hogar',10,'iluminacion-para-el-hogar');
INSERT INTO categories VALUES (128,'Jardín',10,'jardin');
INSERT INTO categories VALUES (129,'Sala y Comedor',10,'sala-y-comedor');
INSERT INTO categories VALUES (11,'Industrias',NULL,'industrias');
INSERT INTO categories VALUES (130,'Construcción',11,'construccion');
INSERT INTO categories VALUES (300,'Máquinas',130,'maquinas');
INSERT INTO categories VALUES (301,'Materiales',130,'materiales');
INSERT INTO categories VALUES (131,'Energía Eléctrica',11,'energia-electrica');
INSERT INTO categories VALUES (132,'Herramientas',11,'herramientas');
INSERT INTO categories VALUES (302,'Eléctricas',132,'electricas');
INSERT INTO categories VALUES (303,'Manuales',132,'manuales');
INSERT INTO categories VALUES (133,'Industria Alimentaria',11,'industria-alimentaria');
INSERT INTO categories VALUES (134,'Industria Textil',11,'industria-textil');
INSERT INTO categories VALUES (304,'Máquinas',134,'maquinas2');
INSERT INTO categories VALUES (305,'Materiales',134,'materiales2');
INSERT INTO categories VALUES (135,'Oficinas',11,'oficinas');
INSERT INTO categories VALUES (306,'Instrumentos y Papelería',135,'instrumentos-y-papeleria');
INSERT INTO categories VALUES (307,'Máquinas de Oficinas',135,'maquinas-de-oficinas');
INSERT INTO categories VALUES (308,'Muebles',135,'muebles');
INSERT INTO categories VALUES (309,'Telefonía',135,'telefonia');
INSERT INTO categories VALUES (136,'Seguridad para Industrias',11,'seguridad-para-industrias');
INSERT INTO categories VALUES (310,'Alarmas y Sensores',136,'alarmas-y-sensores');
INSERT INTO categories VALUES (311,'Cajas Fuertes',136,'cajas-fuertes');
INSERT INTO categories VALUES (312,'Cámaras',136,'camaras');
INSERT INTO categories VALUES (313,'Puertas y Portones',136,'puertas-y-portones');
INSERT INTO categories VALUES (314,'Tarjetas Capturadoras',136,'tarjetas-capturadoras');
INSERT INTO categories VALUES (12,'Instrumentos Musicales',NULL,'instrumentos-musicales');
INSERT INTO categories VALUES (13,'Libros, Música y Películas',NULL,'libros-musica-y-peliculas');
INSERT INTO categories VALUES (14,'Relojes, Joyas y Bisutería',NULL,'relojes-joyas-y-bisuteria');
INSERT INTO categories VALUES (137,'Damas',14,'damas');
INSERT INTO categories VALUES (138,'Caballeros',14,'caballeros');
INSERT INTO categories VALUES (15,'Ropa, Zapatos y Accesorios',NULL,'ropa-zapatos-y-accesorios');
INSERT INTO categories VALUES (139,'Damas',15,'damas2');
INSERT INTO categories VALUES (315,'Accesorios de Moda',139,'accesorios-de-moda');
INSERT INTO categories VALUES (316,'Carteras, Morrales y Billetera',139,'carteras-morrales-y-billetera');
INSERT INTO categories VALUES (317,'Deportivos',139,'deportivos');
INSERT INTO categories VALUES (318,'De Vestir',139,'de-vestir');
INSERT INTO categories VALUES (319,'Casuales',139,'casuales');
INSERT INTO categories VALUES (140,'Caballeros',15,'caballeros2');
INSERT INTO categories VALUES (320,'Accesorios de Moda',140,'accesorios-de-moda2');
INSERT INTO categories VALUES (321,'Carteras, Morrales y Billetera',140,'carteras-morrales-y-billetera2');
INSERT INTO categories VALUES (322,'Deportivos',140,'deportivos2');
INSERT INTO categories VALUES (323,'De Vestir',140,'de-vestir2');
INSERT INTO categories VALUES (324,'Casuales',140,'casuales2');
INSERT INTO categories VALUES (141,'Niños',15,'niños');
INSERT INTO categories VALUES (325,'Accesorios de Moda',141,'accesorios-de-moda3');
INSERT INTO categories VALUES (326,'Carteras, Morrales y Billetera',141,'carteras-morrales-y-billetera3');
INSERT INTO categories VALUES (327,'Deportivos',141,'deportivos3');
INSERT INTO categories VALUES (328,'De Vestir',141,'de-vestir3');
INSERT INTO categories VALUES (329,'Casuales',141,'casuales3');
INSERT INTO categories VALUES (16,'Salud y Belleza',NULL,'salud-y-belleza');
INSERT INTO categories VALUES (142,'Cuidado Personal',16,'cuidado-personal');
INSERT INTO categories VALUES (143,'Equipos para Médicos',16,'equipos-para-medicos');
INSERT INTO categories VALUES (144,'Maquillaje',16,'maquillaje');
INSERT INTO categories VALUES (145,'Perfumes y Fragancias',16,'perfumes-y-fragancias');
INSERT INTO categories VALUES (17,'Asesoría Legal y Fiscal',NULL,'asesoria-legal-y-fiscal');
INSERT INTO categories VALUES (146,'Abogados del área comercial y marítima',17,'abogados-del-area-comercial-y-maritima');
INSERT INTO categories VALUES (147,'Consultoría legal, despacho de abogados',17,'consultoria-legal-despacho-de-abogados');
INSERT INTO categories VALUES (18,'Agentes Aduanales',NULL,'agentes-aduanales');
INSERT INTO categories VALUES (148,'Transporte Internacionales',18,'transporte-internacionales');
INSERT INTO categories VALUES (19,'Corredor Seguros',NULL,'corredor-seguros');
INSERT INTO categories VALUES (149,'Automóvil',19,'automovil');
INSERT INTO categories VALUES (150,'Seguros de Vida',19,'seguros-de-vida');
INSERT INTO categories VALUES (151,'Vivienda',19,'vivienda');
INSERT INTO categories VALUES (20,'Construcción',NULL,'construccion2');
INSERT INTO categories VALUES (152,'Diseño de Proyectos',20,'diseño-de-proyectos');
INSERT INTO categories VALUES (153,'Ingeniero Civil',20,'ingeniero-civil');
INSERT INTO categories VALUES (21,'Electricidad',NULL,'electricidad');
INSERT INTO categories VALUES (154,'Ingeniero Eléctrico',21,'ingeniero-electrico');
INSERT INTO categories VALUES (22,'Mecánica',NULL,'mecanica');
INSERT INTO categories VALUES (155,'Reparación y mantenimiento de motores eléctricos',22,'reparacion-y-mantenimiento-de-motores-electricos');
INSERT INTO categories VALUES (23,'Diseño Gráfico',NULL,'diseño-grafico');
INSERT INTO categories VALUES (156,'Diseño gráfico, identidad corporativa, diseño editorial',23,'diseño-grafico-identidad-corporativa-diseño-editorial');
INSERT INTO categories VALUES (157,'Publicidad, Material Pop, Artes Gráficas',23,'publicidad-material-pop-artes-graficas');
INSERT INTO categories VALUES (24,'Informática',NULL,'informatica');
INSERT INTO categories VALUES (158,'Telecomunicaciones',24,'telecomunicaciones');
INSERT INTO categories VALUES (159,'Redes, cableado estructurado',24,'redes-cableado-estructurado');
INSERT INTO categories VALUES (25,'Turismo',NULL,'turismo');
INSERT INTO categories VALUES (160,'Turismo, Negocio, Correo y Transporte',25,'turismo-negocio-correo-y-transporte');
INSERT INTO categories VALUES (161,'Servicio de Hotelería, Hospedaje, Transporte, Recreación',25,'servicio-de-hoteleria-hospedaje-transporte-recreacion');
INSERT INTO categories VALUES (26,'Médicos',NULL,'medicos');
INSERT INTO categories VALUES (162,'Ambulancias',26,'ambulancias');
INSERT INTO categories VALUES (163,'Consulta',26,'consulta');
INSERT INTO categories VALUES (164,'Emergencias',26,'emergencias');
INSERT INTO categories VALUES (165,'Odontológicos',26,'odontologicos');
INSERT INTO categories VALUES (166,'Oftalmológicos',26,'oftalmologicos');
INSERT INTO categories VALUES (27,'Medios de Comunicación',NULL,'medios-de-comunicacion');
INSERT INTO categories VALUES (167,'Audiovisuales',27,'audiovisuales');
INSERT INTO categories VALUES (168,'Digitales',27,'digitales');
INSERT INTO categories VALUES (169,'Impresos',27,'impresos');
INSERT INTO categories VALUES (28,'Documentos',NULL,'documentos');
INSERT INTO categories VALUES (170,'Tramitación de documentos en general',28,'tramitacion-de-documentos-en-general');
INSERT INTO categories VALUES (171,'Interprete público Español / Italiano - Italiano /Español',28,'interprete-publico-español-/-italiano--italiano-/español');
INSERT INTO categories VALUES (29,'Educación, Aprendizaje y Adiestramiento',NULL,'educacion-aprendizaje-y-adiestramiento');
INSERT INTO categories VALUES (172,'Educacion, Aprendizaje y Adiestramiento',29,'educacion-aprendizaje-y-adiestramiento2');
INSERT INTO categories VALUES (30,'Mantenimiento y Limpieza',NULL,'mantenimiento-y-limpieza');
INSERT INTO categories VALUES (173,'Fumigación, Incineración y Purificación',30,'fumigacion-incineracion-y-purificacion');
INSERT INTO categories VALUES (31,'Mantenimiento Maquinarias',NULL,'mantenimiento-maquinarias');
INSERT INTO categories VALUES (174,'Servicios de Mantenimiento',31,'servicios-de-mantenimiento');
INSERT INTO categories VALUES (32,'Seguridad',NULL,'seguridad');
INSERT INTO categories VALUES (175,'Seguridad - Protección, Seguridad - Control',32,'seguridad--proteccion-seguridad--control');
INSERT INTO categories VALUES (33,'Cursos',NULL,'cursos');
INSERT INTO categories VALUES (176,'Foros, Talleres, Charlas',33,'foros-talleres-charlas');
INSERT INTO categories VALUES (177,'Idiomas',33,'idiomas');
INSERT INTO categories VALUES (34,'Eventos',NULL,'eventos');
INSERT INTO categories VALUES (178,'Organización de Eventos',34,'organizacion-de-eventos');
INSERT INTO categories VALUES (179,'Búsqueda de Sponsors',34,'busqueda-de-sponsors');
INSERT INTO categories VALUES (180,'Caterine',34,'caterine');
INSERT INTO categories VALUES (181,'Salas',34,'salas');
INSERT INTO categories VALUES (35,'Restaurantes',NULL,'restaurantes');
INSERT INTO categories VALUES (182,'Fiestas (Bautizos, Matrimonios, 15 años, Comuniones)',35,'fiestas-(bautizos-matrimonios-15-años-comuniones)');
INSERT INTO categories VALUES (183,'Cenas, Almuerzos corporativos y familiares',35,'cenas-almuerzos-corporativos-y-familiares');
INSERT INTO categories VALUES (36,'Inmuebles',NULL,'inmuebles');
INSERT INTO categories VALUES (184,'Administración de inmuebles, condominios y asesorías',36,'administracion-de-inmuebles-condominios-y-asesorias');
INSERT INTO categories VALUES (37,'Decoración',NULL,'decoracion2');
INSERT INTO categories VALUES (185,'Decoración de interiores en general',37,'decoracion-de-interiores-en-general');
