UPDATE publications_categories SET category_id=1 WHERE category_id>0;
CREATE TABLE publications_temporal AS SELECT * FROM publications_categories GROUP BY publication_id;
DELETE FROM publications_categories WHERE category_id>0;
INSERT INTO publications_categories SELECT * FROM publications_temporal;
DROP TABLE publications_temporal;
UPDATE publishers_categories SET category_id=1 WHERE category_id>0;
CREATE TABLE publishers_temporal AS SELECT * FROM publishers_categories GROUP BY publisher_id;
DELETE FROM publishers_categories WHERE category_id>0;
INSERT INTO publishers_categories SELECT * FROM publishers_temporal;
DROP TABLE publishers_temporal;
UPDATE categories SET category_id=NULL WHERE category_id IS NOT NULL;
DELETE FROM categories WHERE id>1;
UPDATE categories SET  id=1, name='Alimentos y Bebidas', slug='alimentos-y-bebidas' WHERE id=1;
INSERT INTO categories VALUES (50,'Aceites de Oliva y aderezos',1,'Product','aceites-de-oliva-y-aderezos');
INSERT INTO categories VALUES (51,'Alimentos para Bebés',1,'Product','alimentos-para-bebes');
INSERT INTO categories VALUES (52,'Bebidas',1,'Product','bebidas');
INSERT INTO categories VALUES (53,'Café',1,'Product','cafe');
INSERT INTO categories VALUES (54,'Carnes y Aves',1,'Product','carnes-y-aves');
INSERT INTO categories VALUES (55,'Cereales',1,'Product','cereales');
INSERT INTO categories VALUES (56,'Charcutería',1,'Product','charcuteria');
INSERT INTO categories VALUES (57,'Chocolates',1,'Product','chocolates');
INSERT INTO categories VALUES (58,'Delicateses',1,'Product','delicateses');
INSERT INTO categories VALUES (59,'Frutas, Hortalizas y Legumbres',1,'Product','frutas-hortalizas-y-legumbres');
INSERT INTO categories VALUES (60,'Golosinas',1,'Product','golosinas');
INSERT INTO categories VALUES (61,'Licores',1,'Product','licores');
INSERT INTO categories VALUES (62,'Materia Prima',1,'Product','materia-prima');
INSERT INTO categories VALUES (63,'Pastas',1,'Product','pastas');
INSERT INTO categories VALUES (64,'Pastelería y Panadería',1,'Product','pasteleria-y-panaderia');
INSERT INTO categories VALUES (65,'Pescados y Mariscos',1,'Product','pescados-y-mariscos');
INSERT INTO categories VALUES (66,'Productos Navideños',1,'Product','productos-navidenos');
INSERT INTO categories VALUES (67,'Productos Sin Gluten',1,'Product','productos-sin-gluten');
INSERT INTO categories VALUES (68,'Quesos y Lacteos',1,'Product','quesos-y-lacteos');
INSERT INTO categories VALUES (69,'Salsas',1,'Product','salsas');
INSERT INTO categories VALUES (70,'Semi-Elaborados',1,'Product','semi-elaborados');
INSERT INTO categories VALUES (71,'Snack',1,'Product','snack');
INSERT INTO categories VALUES (2,'Accesorios Vehículos, Náuticos y Motos',NULL,'Product','accesorios-vehiculos-nauticos-y-motos');
INSERT INTO categories VALUES (72,'Accesorios y Repuestos Náuticos',2,'Product','accesorios-y-repuestos-nauticos');
INSERT INTO categories VALUES (73,'Accesorios y Repuestos para Carros',2,'Product','accesorios-y-repuestos-para-carros');
INSERT INTO categories VALUES (74,'Accesorios y Repuestos para Motos',2,'Product','accesorios-y-repuestos-para-motos');
INSERT INTO categories VALUES (75,'Accesorios y Repuestos para Rústicos',2,'Product','accesorios-y-repuestos-para-rusticos');
INSERT INTO categories VALUES (3,'Animales y Mascotas',NULL,'Product','animales-y-mascotas');
INSERT INTO categories VALUES (76,'Alimentación para Animales',3,'Product','alimentacion-para-animales');
INSERT INTO categories VALUES (77,'Accesorios Aves',3,'Product','accesorios-aves');
INSERT INTO categories VALUES (78,'Accesorios Caballos',3,'Product','accesorios-caballos');
INSERT INTO categories VALUES (79,'Accesorios Ganado',3,'Product','accesorios-ganado');
INSERT INTO categories VALUES (80,'Accesorios para Peceras',3,'Product','accesorios-para-peceras');
INSERT INTO categories VALUES (4,'Art. Electrónicos y Electrodomésticos',NULL,'Product','art-electronicos-y-electrodomesticos');
INSERT INTO categories VALUES (81,'Accesorios para Audio y Video',4,'Product','accesorios-para-audio-y-video');
INSERT INTO categories VALUES (82,'Accesorios para Cámaras',4,'Product','accesorios-para-camaras');
INSERT INTO categories VALUES (83,'Accesorios para Celulares',4,'Product','accesorios-para-celulares');
INSERT INTO categories VALUES (84,'Accesorios para Laptops',4,'Product','accesorios-para-laptops');
INSERT INTO categories VALUES (85,'Aires Acondicionados',4,'Product','aires-acondicionados');
INSERT INTO categories VALUES (86,'Artefactos para el Hogar',4,'Product','artefactos-para-el-hogar');
INSERT INTO categories VALUES (87,'Audio para Carros',4,'Product','audio-para-carros');
INSERT INTO categories VALUES (88,'Audio para el Hogar',4,'Product','audio-para-el-hogar');
INSERT INTO categories VALUES (89,'Audio Portátil y Radios',4,'Product','audio-portatil-y-radios');
INSERT INTO categories VALUES (90,'Audio Profesional y DJs',4,'Product','audio-profesional-y-djs');
INSERT INTO categories VALUES (91,'Calculadoras',4,'Product','calculadoras');
INSERT INTO categories VALUES (92,'Cámaras Convencionales',4,'Product','camaras-convencionales');
INSERT INTO categories VALUES (93,'Cámaras Digitales',4,'Product','camaras-digitales');
INSERT INTO categories VALUES (94,'Cartuchos, Tintas y Toner',4,'Product','cartuchos-tintas-y-toner');
INSERT INTO categories VALUES (95,'Celulares',4,'Product','celulares');
INSERT INTO categories VALUES (96,'Computadoras',4,'Product','computadoras');
INSERT INTO categories VALUES (97,'Discos Duros y Removibles',4,'Product','discos-duros-y-removibles');
INSERT INTO categories VALUES (98,'DVDs y Home Theaters',4,'Product','dvds-y-home-theaters');
INSERT INTO categories VALUES (99,'Electrodomésticos de Cocina',4,'Product','electrodomesticos-de-cocina');
INSERT INTO categories VALUES (100,'Fotocopiadoras y Accesorios',4,'Product','fotocopiadoras-y-accesorios');
INSERT INTO categories VALUES (101,'GPS y Accesorios',4,'Product','gps-y-accesorios');
INSERT INTO categories VALUES (102,'Impresoras y Plotters',4,'Product','impresoras-y-plotters');
INSERT INTO categories VALUES (103,'iPad y Tablets',4,'Product','ipad-y-tablets');
INSERT INTO categories VALUES (104,'Laptops',4,'Product','laptops');
INSERT INTO categories VALUES (105,'Lavadoras y Secadoras',4,'Product','lavadoras-y-secadoras');
INSERT INTO categories VALUES (106,'Memorias Digitales',4,'Product','memorias-digitales');
INSERT INTO categories VALUES (107,'Memorias Portátiles USB',4,'Product','memorias-portatiles-usb');
INSERT INTO categories VALUES (108,'Memorias RAM',4,'Product','memorias-ram');
INSERT INTO categories VALUES (109,'Monitores',4,'Product','monitores');
INSERT INTO categories VALUES (110,'Neveras y Congeladores',4,'Product','neveras-y-congeladores');
INSERT INTO categories VALUES (111,'Periféricos y Accesorios de PC',4,'Product','perifericos-y-accesorios-de-pc');
INSERT INTO categories VALUES (112,'Procesadores',4,'Product','procesadores');
INSERT INTO categories VALUES (113,'Proyectores y Pantallas',4,'Product','proyectores-y-pantallas');
INSERT INTO categories VALUES (114,'Radios - WalkieTalkies',4,'Product','radios-walkietalkies');
INSERT INTO categories VALUES (115,'Redes Inalámbricas y No Inalámbricas',4,'Product','redes-inalambricas-y-no-inalambricas');
INSERT INTO categories VALUES (116,'Registradoras y Punto de Venta',4,'Product','registradoras-y-punto-de-venta');
INSERT INTO categories VALUES (117,'Reproductores MP3, MP4 y MP5',4,'Product','reproductores-mp3-mp4-y-mp5');
INSERT INTO categories VALUES (118,'Seguridad para el Hogar',4,'Product','seguridad-para-el-hogar');
INSERT INTO categories VALUES (119,'Software',4,'Product','software');
INSERT INTO categories VALUES (120,'Tarjetas de Video y Captura',4,'Product','tarjetas-de-video-y-captura');
INSERT INTO categories VALUES (121,'Tarjetas Madre',4,'Product','tarjetas-madre');
INSERT INTO categories VALUES (122,'Telefonía',4,'Product','telefonia');
INSERT INTO categories VALUES (123,'Televisores',4,'Product','televisores');
INSERT INTO categories VALUES (124,'Ventiladores',4,'Product','ventiladores');
INSERT INTO categories VALUES (125,'Video Cámaras',4,'Product','video-camaras');
INSERT INTO categories VALUES (5,'Deportes y Fitness',NULL,'Product','deportes-y-fitness');
INSERT INTO categories VALUES (126,'Aerobics y Fitness',5,'Product','aerobics-y-fitness');
INSERT INTO categories VALUES (127,'Artes Marciales y Boxeo',5,'Product','artes-marciales-y-boxeo');
INSERT INTO categories VALUES (128,'Beisbol, Futból, Basquet, Tenis, Golf',5,'Product','beisbol-futbol-basquet-tenis-golf');
INSERT INTO categories VALUES (129,'Bicicletas y Ciclismo',5,'Product','bicicletas-y-ciclismo');
INSERT INTO categories VALUES (130,'Camping',5,'Product','camping');
INSERT INTO categories VALUES (131,'Deportes Acuáticos',5,'Product','deportes-acuaticos');
INSERT INTO categories VALUES (132,'Deportes Extremos',5,'Product','deportes-extremos');
INSERT INTO categories VALUES (133,'Equipos para Pesca',5,'Product','equipos-para-pesca');
INSERT INTO categories VALUES (134,'Lentes Deportivos y de Sol',5,'Product','lentes-deportivos-y-de-sol');
INSERT INTO categories VALUES (135,'Máquinas de Gimnasio',5,'Product','maquinas-de-gimnasio');
INSERT INTO categories VALUES (136,'Morrales, Koalas y Maletines',5,'Product','morrales-koalas-y-maletines');
INSERT INTO categories VALUES (6,'Hogar y Muebles',NULL,'Product','hogar-y-muebles');
INSERT INTO categories VALUES (137,'Baño',6,'Product','bano');
INSERT INTO categories VALUES (138,'Artículos de Bebés para Baño',6,'Product','articulos-de-bebes-para-bano');
INSERT INTO categories VALUES (139,'Cocina',6,'Product','cocina');
INSERT INTO categories VALUES (140,'Decoración',6,'Product','decoracion');
INSERT INTO categories VALUES (141,'Dormitorio',6,'Product','dormitorio');
INSERT INTO categories VALUES (142,'Herramientas para el Hogar',6,'Product','herramientas-para-el-hogar');
INSERT INTO categories VALUES (143,'Iluminación para el Hogar',6,'Product','iluminacion-para-el-hogar');
INSERT INTO categories VALUES (144,'Jardín',6,'Product','jardin');
INSERT INTO categories VALUES (145,'Sala y Comedor',6,'Product','sala-y-comedor');
INSERT INTO categories VALUES (7,'Industrias',NULL,'Product','industrias');
INSERT INTO categories VALUES (146,'Alarmas y Sensores',7,'Product','alarmas-y-sensores');
INSERT INTO categories VALUES (147,'Herramientas Eléctricas',7,'Product','herramientas-electricas');
INSERT INTO categories VALUES (148,'Herramientas Manuales',7,'Product','herramientas-manuales');
INSERT INTO categories VALUES (149,'Instrumentos y Papelería',7,'Product','instrumentos-y-papeleria');
INSERT INTO categories VALUES (150,'Máquinas',7,'Product','maquinas');
INSERT INTO categories VALUES (151,'Materiales',7,'Product','materiales');
INSERT INTO categories VALUES (152,'Muebles',7,'Product','muebles');
INSERT INTO categories VALUES (153,'Puertas y Portones',7,'Product','puertas-y-portones');
INSERT INTO categories VALUES (154,'Tarjetas Capturadoras',7,'Product','tarjetas-capturadoras');
INSERT INTO categories VALUES (8,'Instrumentos, Libros, Música y Películas',NULL,'Product','instrumentos-libros-musica-y-peliculas');
INSERT INTO categories VALUES (9,'Ropa, Zapatos, Relojes, Joyas',NULL,'Product','ropa-zapatos-relojes-joyas');
INSERT INTO categories VALUES (155,'Accesorios de Moda',9,'Product','accesorios-de-moda');
INSERT INTO categories VALUES (156,'Accesorios para Bebés',9,'Product','accesorios-para-bebes');
INSERT INTO categories VALUES (157,'Carteras, Morrales y Billetera',9,'Product','carteras-morrales-y-billetera');
INSERT INTO categories VALUES (158,'Casuales',9,'Product','casuales');
INSERT INTO categories VALUES (159,'De Vestir',9,'Product','de-vestir');
INSERT INTO categories VALUES (160,'Deportivos',9,'Product','deportivos');
INSERT INTO categories VALUES (10,'Salud y Belleza',NULL,'Product','salud-y-belleza');
INSERT INTO categories VALUES (161,'Cuidado Personal',10,'Product','cuidado-personal');
INSERT INTO categories VALUES (162,'Equipos para Médicos',10,'Product','equipos-para-medicos');
INSERT INTO categories VALUES (163,'Maquillaje',10,'Product','maquillaje');
INSERT INTO categories VALUES (164,'Perfumes y Fragancias',10,'Product','perfumes-y-fragancias');
INSERT INTO categories VALUES (11,'Asesoría Legal, Aduanas y Aseguración',NULL,'Service','asesoria-legal-aduanas-y-aseguracion');
INSERT INTO categories VALUES (165,'Abogados del Área comercial y maritima',11,'Service','abogados-del-area-comercial-y-maritima');
INSERT INTO categories VALUES (166,'Consultoria legal, despacho de abogados',11,'Service','consultoria-legal-despacho-de-abogados');
INSERT INTO categories VALUES (167,'Tramitación de documentos en general',11,'Service','tramitacion-de-documentos-en-general');
INSERT INTO categories VALUES (168,'Interprete público Español / Italiano - Italiano /Español',11,'Service','interprete-publico-espanol/italiano-italiano/espanol');
INSERT INTO categories VALUES (169,'Seguros de Automovil',11,'Service','seguros-de-automovil');
INSERT INTO categories VALUES (170,'Seguros de Vida',11,'Service','seguros-de-vida');
INSERT INTO categories VALUES (171,'Seguros de Vivienda',11,'Service','seguros-de-vivienda');
INSERT INTO categories VALUES (172,'Transporte Internacionales',11,'Service','transporte-internacionales');
INSERT INTO categories VALUES (12,'Construcción en General e Inmuebles',NULL,'Service','construccion-en-general-e-inmuebles');
INSERT INTO categories VALUES (173,'Administración de Inmuebles, condominios y asesorias',12,'Service','administracion-de-inmuebles-condominios-y-asesorias');
INSERT INTO categories VALUES (174,'Arquitectura',12,'Service','arquitectura');
INSERT INTO categories VALUES (175,'Diseño de Proyectos',12,'Service','diseno-de-proyectos');
INSERT INTO categories VALUES (176,'Ingeniero Civil',12,'Service','ingeniero-civil');
INSERT INTO categories VALUES (177,'Ingeniero Eléctrico',12,'Service','ingeniero-electrico');
INSERT INTO categories VALUES (178,'Plomería',12,'Service','plomeria');
INSERT INTO categories VALUES (13,'Mecánica, Metalmecánica',NULL,'Service','mecanica-metalmecanica');
INSERT INTO categories VALUES (179,'Reparación y mantenimiento de motores eléctricos',13,'Service','reparacion-y-mantenimiento-de-motores-electricos');
INSERT INTO categories VALUES (14,'Turismo',NULL,'Service','turismo');
INSERT INTO categories VALUES (180,'Turismo, Negocio, Correo y Transporte',14,'Service','turismo-negocio-correo-y-transporte');
INSERT INTO categories VALUES (181,'Servicio de Hotelería, Hospedaje, Transporte, Recreación',14,'Service','servicio-de-hoteleria-hospedaje-transporte-recreacion');
INSERT INTO categories VALUES (15,'Médicos',NULL,'Service','medicos');
INSERT INTO categories VALUES (182,'Ambulancias',15,'Service','ambulancias');
INSERT INTO categories VALUES (183,'Consulta',15,'Service','consulta');
INSERT INTO categories VALUES (184,'Emergencias',15,'Service','emergencias');
INSERT INTO categories VALUES (185,'Servicios Médicos',15,'Service','servicios-medicos');
INSERT INTO categories VALUES (16,'Diseño, Informática y Telecomunicaciones',NULL,'Service','diseno-informatica-y-telecomunicaciones');
INSERT INTO categories VALUES (186,'Audiovisuales',16,'Service','audiovisuales');
INSERT INTO categories VALUES (187,'Telecomunicaciones',16,'Service','telecomunicaciones');
INSERT INTO categories VALUES (188,'Redes, cableado estructurado',16,'Service','redes-cableado-estructurado');
INSERT INTO categories VALUES (189,'Digitales',16,'Service','digitales');
INSERT INTO categories VALUES (190,'Diseño gráfico, identidad corporativa, diseño editorial',16,'Service','diseno-grafico-identidad-corporativa-diseno-editorial');
INSERT INTO categories VALUES (191,'Impresos',16,'Service','impresos');
INSERT INTO categories VALUES (192,'Publicidad, Material Pop, Artes Graficas',16,'Service','publicidad-material-pop-artes-graficas');
INSERT INTO categories VALUES (17,'Aprendizaje y Adiestramiento',NULL,'Service','aprendizaje-y-adiestramiento');
INSERT INTO categories VALUES (193,'Foros, Talleres, Charlas',17,'Service','foros-talleres-charlas');
INSERT INTO categories VALUES (194,'Educacion, Aprendizaje y Adiestramiento',17,'Service','educacion-aprendizaje-y-adiestramiento');
INSERT INTO categories VALUES (195,'Idiomas',17,'Service','idiomas');
INSERT INTO categories VALUES (18,'Decoración, Mantenimiento y Limpieza',NULL,'Service','decoracion-mantenimiento-y-limpieza');
INSERT INTO categories VALUES (196,'Decoración de interiores en general',18,'Service','decoracion-de-interiores-en-general');
INSERT INTO categories VALUES (197,'Fumigación, Incineración y Purificación',18,'Service','fumigacion-incineracion-y-purificacion');
INSERT INTO categories VALUES (19,'Mantenimiento de equipos industriales',NULL,'Service','mantenimiento-de-equipos-industriales');
INSERT INTO categories VALUES (198,'Servicios de Mantenimiento',19,'Service','servicios-de-mantenimiento');
INSERT INTO categories VALUES (20,'Restaurantes, Eventos y Seguridad',NULL,'Service','restaurantes-eventos-y-seguridad');
INSERT INTO categories VALUES (199,'Búsqueda de Sponsors',20,'Service','busqueda-de-sponsors');
INSERT INTO categories VALUES (200,'Caterine',20,'Service','caterine');
INSERT INTO categories VALUES (201,'Cenas, Almuerzos corporativos y familiares',20,'Service','cenas-almuerzos-corporativos-y-familiares');
INSERT INTO categories VALUES (202,'Fiestas (Bautizos, matrimonios, 15 años, Comuniones)',20,'Service','fiestas-(bautizos-matrimonios-15-anos-comuniones)');
INSERT INTO categories VALUES (203,'Organización de Eventos',20,'Service','organizacion-de-eventos');
INSERT INTO categories VALUES (204,'Seguridad - Proteccion, Seguridad - Control',20,'Service','seguridad-proteccion-seguridad-control');
INSERT INTO categories VALUES (205,'Salas',20,'Service','salas');
/*Entrar por publicación y publisher y asignar categorías que le correspondan*/
